documents:
    type: rest
    resource: AppBundle\Controller\DocumentController

forms:
    type: rest
    resource: AppBundle\Controller\FormController

document_category:
    type: rest
    resource: AppBundle\Controller\DocumentCategoryController

login:
    type: rest
    resource: AppBundle\Controller\RestLoginController

password_management:
    type: rest
    resource: AppBundle\Controller\RestPasswordManagementController

profile:
    type: rest
    resource: AppBundle\Controller\RestProfileController

registration:
    type: rest
    resource: AppBundle\Controller\RestRegistrationController
    
payments:
    type: rest
    resource: AppBundle\Controller\PaymentController 

files:
    type: rest
    resource: AppBundle\Controller\FileController