documents:
    type: rest
    resource: AppBundle\Controller\DocumentController

document_category:
    type: rest
    resource: AppBundle\Controller\DocumentCategoryController

login:
    type: rest
    resource: AppBundle\Controller\RestLoginController

password_management:
    type: rest
    resource: AppBundle\Controller\RestPasswordManagementController

profile:
    type: rest
    resource: AppBundle\Controller\RestProfileController

registration:
    type: rest
    resource: AppBundle\Controller\RestRegistrationController