documents:
    type: rest
    resource: AppBundle\Controller\DocumentController

texts:
    type: rest
    resource: AppBundle\Controller\ReadyTextController

categories:
    type: rest
    resource: AppBundle\Controller\CategoryController

forms:
    type: rest
    resource: AppBundle\Controller\FormController

questions:
    type: rest
    resource: AppBundle\Controller\QuestionController

options:
    type: rest
    resource: AppBundle\Controller\OptionController

answers:
    type: rest
    resource: AppBundle\Controller\AnswerController

login:
    type: rest
    resource: AppBundle\Controller\RestLoginController

password_management:
    type: rest
    resource: AppBundle\Controller\RestPasswordManagementController

profile:
    type: rest
    resource: AppBundle\Controller\RestProfileController

registration:
    type: rest
    resource: AppBundle\Controller\RestRegistrationController

files:
    type: rest
    resource: AppBundle\Controller\FileController
    
orders:
    type: rest
    resource: AppBundle\Controller\OrderController