security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:        
#        main:
#            pattern: ^/
#            form_login:
#                provider: fos_userbundle
#                csrf_token_generator: security.csrf.token_manager
#            logout:       true
#            anonymous:    true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_docs:
            pattern: ^/doc
            anonymous: true

        api_password_reset:
            pattern: ^/password/reset
            anonymous: true

        api_login:
            pattern:  ^/login$
            stateless: true
            anonymous: true
            form_login:
                check_path:               /login
                require_previous_session: false
                username_parameter:       username
                password_parameter:       password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        api_register:
            pattern: ^/register
            anonymous: true

        api_documents:
            pattern: ^/documents
            anonymous: true

        api_texts:
            pattern: ^/texts
            anonymous: true

        api_forms:
            pattern: ^/forms
            anonymous: true

        api_questions:
            pattern: ^/questions
            anonymous: true

        api_options:
            pattern: ^/options
            anonymous: true

        api_categories:
            pattern: ^/categories
            anonymous: true

        api_payment:
            pattern: ^/payments
            anonymous: true

        api_setting:
            pattern: ^/settings
            anonymous: true

        api_files:
            pattern: ^/files
            anonymous: true


#        login:
#            pattern:  ^/api/login
#            stateless: true
#            anonymous: true
#            form_login:
#                check_path:               /api/login_check
#                success_handler:          lexik_jwt_authentication.handler.authentication_success
#                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
#                require_previous_session: false

        api:
            pattern:   ^/
            stateless: true
            lexik_jwt: ~
#            guard:
#                authenticators:
#                    - lexik_jwt_authentication.jwt_token_authenticator

#symfony.com/doc/current/security/access_control.html
#host: www.yourdomain.com
#- { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/password/reset, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/documents, roles: IS_AUTHENTICATED_ANONYMOUSLY, ips: [127.0.0.1, ::1] }
        - { path: ^/documents, roles: ROLE_NO_ACCESS }
        - { path: ^/texts, role: IS_AUTHENTICATED_ANONYMOUSLY, ips: [127.0.0.1, ::1] }
        - { path: ^/texts, roles: ROLE_NO_ACCESS }
        - { path: ^/forms, role: IS_AUTHENTICATED_ANONYMOUSLY, ips: [127.0.0.1, ::1] }
        - { path: ^/forms, roles: ROLE_NO_ACCESS }
        - { path: ^/questions, role: IS_AUTHENTICATED_ANONYMOUSLY, ips: [127.0.0.1, ::1] }
        - { path: ^/questions, roles: ROLE_NO_ACCESS } 
        - { path: ^/options, role: IS_AUTHENTICATED_ANONYMOUSLY, ips: [127.0.0.1, ::1] }
        - { path: ^/options, roles: ROLE_NO_ACCESS }        
        - { path: ^/categories, role: IS_AUTHENTICATED_ANONYMOUSLY, ips: [127.0.0.1, ::1] }
        - { path: ^/categories, roles: ROLE_NO_ACCESS }
        - { path: ^/payments, role: IS_AUTHENTICATED_ANONYMOUSLY, ips: [127.0.0.1, ::1] }
        - { path: ^/payments, roles: ROLE_NO_ACCESS }
        - { path: ^/settings, role: IS_AUTHENTICATED_ANONYMOUSLY, ips: [127.0.0.1, ::1] }
        - { path: ^/settings, roles: ROLE_NO_ACCESS }        
        - { path: ^/files, role: IS_AUTHENTICATED_ANONYMOUSLY, ips: [127.0.0.1, ::1] }
        - { path: ^/files, roles: ROLE_NO_ACCESS }        
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }